apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node-app
      version: 1.20.1
  template:
    metadata:
      name: hello-node-pod
      labels:
        app: hello-node-app
        version: 1.20.1
    spec:
      containers:
      - name: hello-node-container
        image: renugunta88/node:BUILDNUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
  labels:
    app: hello-node-app
spec:
  selector:
    app: hello-node-app
    version: 1.20.1
  type: NodePort
  ports:
  - nodePort: 31123
    port: 5000
    targetPort: 5000